# Generated by Django 4.2.6 on 2023-12-06 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicles', '0005_alter_vehicle_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='available',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Vehicles.office'),
        ),
    ]
